### ISSUE TITLE
Incompatible with `exasol-testcontainers` 3.5.2

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/udf-debugging-java#17]
## Problem 

 The library is not compatible with `exasol-testcontainers` 3.5.2.
With 3.5.1 it works fine.

## Error message

```
java.lang.IncompatibleClassChangeError: Found interface com.exasol.bucketfs.Bucket, but class was expected
```

## How to reproduce

new UdfTestSetup(EXASOL.getHostIp(), EXASOL.getDefaultBucket());

**Comment by jakobbraun** [comment]
This should be solved by #11
